### ISSUE TITLE
AI generated content risks trustworthiness of the platform

### ISSUE THREAD

**Issue by chrisn** [w3c/ai-web-impact#5]
In Section 4.5 I suggest adding another undesirable outcome to the list: Given that LLMs are language generators, whose output may or may not be accurate or truthful (some call this “hallucination”, but this term is misleading), and because of incentives for publishing at scale (e.g., monetisation through ads), there is a risk of the platform becoming less useful and trustworthy overall for consumers, the more that AI generated content is produced and distributed.

**Comment by dontcallmedom** [comment]
That topic is (meant to be) covered in [4.1.1 "Transparency on AI-generated content"](https://www.w3.org/reports/ai-web-impact/#transparency-on-ai-generated-content):
> it creates a systemic risk for content consumers in no longer being able to distinguish or discover authoritative or curated content in a sea of credible (but either possibly or wilfully wrong) generated content.

Is there a different angle that you think should be covered in the context of [4.5 "Balancing content creators incentives and consumers rights"](https://www.w3.org/reports/ai-web-impact/#balancing-content-creators-incentives-and-consumers-rights)? or additional description needed on this point in 4.1.1?

**Comment by chrisn** [comment]
It does, and re-reading it I think it's OK as is.
