### ISSUE TITLE
Implied contract and pointing to sources

### ISSUE THREAD

**Issue by chrisn** [w3c/ai-web-impact#6]
In Section 4.5.1, the bullet point about the implicit contract, and pointing back to sources, it's worth adding that it's also not obvious that such solutions result in a good balance for content creators.

**Comment by dontcallmedom** [comment]
could you help qualify more specifically what this isn't a good balance? I imagine two aspects make this less good than the search engines model:
* fewer relevant sources being exposed
* less incentives to visit the sources if the AI system has already provided (what at least looks like) the specific answer

**Comment by chrisn** [comment]
Yes, it's both of those things. For any given topic, a search engine is likely to return a larger number of sources. And because of the interactive nature of LLM AI interfaces, users may well prefer to stay there rather than visit the sources, reducing the creator's ability to build its own audience, or for users even to recognise that the value they received in getting an answer is attributable to the original sources.

**Comment by dontcallmedom** [comment]
I've filed https://github.com/w3c/ai-web-impact/pull/12 with some proposed related additions
